### ISSUE TITLE
eval data loader 

### ISSUE THREAD

**Issue by evolvingai** [shaoren-sim/pytorch-image-classification-template#1]
Hello

I see that for eval data loader you are using the train dataset. Was that intentional?

**Comment by shaoren-sim** [comment]
Hi, that was an unintentional bug from my side that I missed, it should definitely be using the evaluation dataset.

Will get it fixed as soon as possible.

Thanks for catching the issue.

**Comment by shaoren-sim** [comment]
Fixed the issue and merged with https://github.com/shaoren-sim/pytorch-image-classification-template/pull/2

Thanks once again for catching the bug. Hope this didn't cause too much issues on your end.

Do let me know if you have any other problems.

**Comment by evolvingai** [comment]
No worries, I was testing and the metrics seemed to good :)
